################################# Default configuration ###################
baseURL = "https://neoslide.mk"
title = "NeoSlide"
theme = "neoslide-web"
# post pagination
paginate = "12"
# post excerpt
summaryLength = "15"
# disqus short name
#disqusShortname = "" # get your shortname form here : https://disqus.com

DefaultContentLanguage = "mk"
# disable language
#disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################
[[menu.main]]
name = "about"
URL = "about"
weight = 1

[[menu.main]]
name = "services"
URL = "services"
weight = 4

#[[menu.main]]
#name = "portfolio"
#URL = "portfolio"
#weight = 3

# [[menu.main]]
# name = "team"
# URL = "team"
# weight = 4

# [[menu.main]]
# name = "pricing"
# URL = "pricing"
# weight = 5

[[menu.main]]
name = "blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "contact"
URL = "contact"
weight = 9

#### external / static link ####
#[[menu.static]]
#name = "themefisher"
#URL = "https://themefisher.com/"
#weight = 8

############################# Default Parameters ##########################
[params]
logo = "images/neoslide_full.png"
# Meta data
description = "Modern digital signage platform"
author = "NeoSlide"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/neoslide_icon.png"

# google map
# [params.map]
# enable = true
# gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
# map_latitude = "51.5223477"
# map_longitude = "-0.1622023"
# map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/NeoSlide-108408134207388/?view_public_for=108408134207388"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/neoslide.mk/"

################################ Macedonian Language ########################
[Languages.mk]
languageName = "Mk"
languageCode = "mk-mk"
contentDir = "content/macedonian"
weight = 1
home = "Почеток"
copyright = "Copyright &copy; 2021 NeoSlide.mk"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
home = "Home"
copyright = "Copyright &copy; 2021 NeoSlide.mk"

